* Bookmarks
** What is this about?

   When I find an interesting article or video, I share it here. Most
   of these are possible starting points for a short presentation, or
   may be useful for your application research.

   I usually look at the articles in some detail (though I rarely work
   through them - that would be your job), and assign a label for the
   difficulty level Lvl = 0 (simple), 1 (moderate), 2 (difficult), or 3
   (hard).

   Papers can be hard for different reason: length, technical
   vocabulary, writing style, mathematics, number of citations etc. If
   you find any of these interesting and want to use them for your
   research, you might ask me why I assigned a particular level.

** Machine Learning's crumbling foundations (Lvl=0)

   Doctorow, C (19 Aug 2021). Machine learning's crumbling
   foundations. Doing 'data science' with bad data [Blog]. Online:
   [[https://doctorow.medium.com/machine-learnings-crumbling-foundations-bd11efa22b0][doctorow.medium.com]].

   #+begin_quote
   »Technological debt is insidious, a kind of socio-infrastructural
   subprime crisis that’s unfolding around us in slow motion. Our digital
   infrastructure is built atop layers and layers and layers of code
   that’s insecure due to a combination of bad practices and bad
   frameworks.«
   #+end_quote

** AI explainability (Lvl=1)

   McDermid JA, Jia Y, Porter Z, Habli I. 2021 Artificial
   intelligence explainability: the technical and ethical
   dimensions. In: Phil. Trans. R. Soc. A 379: 20200363.
   https://doi.org/10.1098/rsta.2020.0363

   #+begin_quote
   »The use of critical ML-based systems to assist or to replace the human decision-maker raises many
   questions about when, and whether, we should trust them. AI explainability (XAI) methods are
   part of the answer. The use of XAI methods can contribute to building assurance, or justified
   confidence, in critical systems employing ML.«
   #+end_quote

** Use of AI in smart buildings (LvL=2)

   /Literature reviews are among the most important papers, both for beginners (to get an overview), and for experts (to keep their overview) - because they wade through and evaluate many articles in one fell swoop. You may still have to go back to the original source, but no matter what, you'll have saved a lot of time, and learnt a lot, because the authors of literature reviews are often experts themselves (or becoming experts, by writing a literature review). Also, a literature review should be a part of every paper you write, and of every presentation you give./

   Aguilar et al (2021). A systematic literature review on the
   use of artificial intelligence in energy self-management in smart
   buildings. In: Renewable and Sustainable Energy
   Reviews 151. https://doi.org/10.1016/j.rser.2021.111530

   #+begin_quote
   »Buildings are one of the main consumers of energy in cities, which
   is why a lot of research has been generated around this
   problem. Especially, the buildings energy management systems must
   improve in the next years. Artificial intelligence techniques are
   playing and will play a fundamental role in these
   improvements. This work presents a systematic review of the
   literature on researches that have been done in recent years to
   improve energy management systems for smart building using
   artificial intelligence techniques.«
   #+end_quote

** Computing Machinery and Intelligence (1947) (Lvl=1)

   [[https://www.csee.umbc.edu/courses/471/papers/turing.pdf][Turing AM (1950). Computing Machinery and Intelligence. Mind 49:
   433-460.]]

   #+begin_quote
   »I propose to consider the question, "Can machines think?" This should begin with
   definitions of the meaning of the terms "machine" and "think." The definitions might be
   framed so as to reflect so far as possible the normal use of the words, but this attitude is
   dangerous, If the meaning of the words "machine" and "think" are to be found by
   examining how they are commonly used it is difficult to escape the conclusion that the
   meaning and the answer to the question, "Can machines think?" is to be sought in a
   statistical survey such as a Gallup poll. But this is absurd.«
   #+end_quote

** AI Trends 2021 (Lvl=1)

   Stanford University, Institute for Human-centered Artificial
   Intelligence (2021). AI Index Report. [[https://aiindex.stanford.edu/report/][Online: aiindex.stanford.edu.]]

   #+begin_quote
   "The 2021 report also shows the effects of COVID-19 on AI development
   from multiple perspectives. The Technical Performance chapter
   discusses how an AI startup used machine-learning-based techniques to
   accelerate COVID-related drug discovery during the pandemic, and our
   Economy chapter suggests that AI hiring and private investment were
   not significantly adversely influenced by the pandemic, as both grew
   during 2020. If anything, COVID-19 may have led to a higher number of
   people participating in AI research conferences, as the pandemic
   forced conferences to shift to virtual formats, which in turn led to
   significant spikes in attendance."
   #+end_quote

** Bot Doc (Lvl=0)

   Feldman A/Pratap A (2021). Bot Doc. In: Forbes, August/September
   2021:37-39.

   #+begin_quote
   "Two zoung MIT grads and a bariatric surgeon are gambling on a new
   miniature surgical robot to make abdominal surgery faster, safer
   and cheaper - and beat the industry's goliath."
   #+end_quote

   /I read this in the library and thought it was very interesting, with lots of potential for clarification. The article is very short and focuses mainly on the commercial and market issues. In some
   ways, this is a typical startup story./

