* What is this?

  This is a Frequently Asked Questions (FAQ) file for the special
  seminar on "Artificial Intelligence" (CSC 482.01). For the FAQs
  across courses, see the [[https://github.com/birkenkrahe/org][org repo]].

* Can we use any AI application for our presentation?

  Yes, absolutely. To base your presentation on AIMA is probably
  easiest, since it is up to date (2021), and you'll find all necessary
  sources in one place[fn:1], but it's also a little dull.

  Several alternatives were listed in the syllabus:
  * Present a (sub)chapter from AIMA (or from another book),
    e.g. chapter 13.5 on "Causal Networks". These few pages pack a
    punch, and to understand and unpack them, you may need to read
    some of the "Book of Why" by Judeah Pearl ([[pearl19][Pearl, 2018]])
  * Review and present an AI research paper - this could e.g. be a
    historical article, like Samuel's seminal paper on AI ([[samuel57][Samuel,
    1957]]).
  * Find an interesting application and research it. Your emphasis
    could be technical ("how/why does it work?"), commercial
    ("what's the business model?"), philosophical ("what does this
    mean for life, society, you?"), psychological, anthropological
    etc. This last project may also make the development of your own
    application easier.
  * Propose a presentation format and background that I haven't
    thought of. E.g. based on an experience you made, or even
    something more fantastical and speculative (like sci-fi) would
    be possible - but you have to research it systematically.

  To give you ideas, I have started [[https://github.com/birkenkrahe/ai482/blob/main/bookmarks.md][this file with bookmarks]] of
  interesting articles that you might use for your presentation. Check
  it out.

* References

  <<pearl19>> [[https://www.amazon.com/Book-Why-Science-Cause-Effect/dp/1541698967/][Pearl J, Mackenzie D (2018). The Book of Why. Penguin.]]

  <<samuel57>> [[https://www.cs.virginia.edu/~evans/greatworks/samuel.pdf][Samuel A L (1959). Some Studies in Machine Learning
  Using the Game of Checkers. IBM Journal 3(3) 1959:535-554.]]

* Footnotes

[fn:1]You'll still need to do some research: the AIMA chapters are
quite densely written, and need to be unpacked. The chapters have
their own references, which you should look up and check, too.
