#+startup: overview
* Session Protocols

  Post your protocol here. Take a look at [[https://github.com/birkenkrahe/ai482/blob/main/2_what_is_ai/protocol_23_aug.md][my example protocol]].

  I have not written protocols for every talk but every speaker should
  have received feedback from me via email at least.

* [[https://github.com/birkenkrahe/ai482/blob/main/presentations/Sampley_Autonomous%20Drones%20in%20the%20U.S.%20Military.pdf][AI in the military (Jacob Sampley, 13-Oct-2021)]]

  This presentation was totally worth staying up for all night - very
  well done (apart from Jacob's time mgmt prior to the presentation
  ;-). A great start to the solo presentation series! Jacob really
  used his time well: the number of slides was just right for 45
  min. 30 min speaking + discussion.

  I hope to pick this up at the start on Wed, perhaps re: technology,
  because we didn't talk about that at all.

  Some potential points of improvement[fn:1]:

  1) There was a clear *research question*, in the subtitle (perhaps
     even a *hypothesis*?). It would have been good to directly answer
     it at the end, "main message" style. Like a paper, a presentation
     benefits from a summary/conclusion. All the information was
     there, on the slides, which were partly organized like a
     paper[fn:2].
  2) *Audience interaction*: questions to the audience should always
     be *open questions* if you want a discussion, and only closed
     questions for a poll-like interaction (which does wake people
     up): it's sometimes good to ask these throughout the talk.
  3) *Graphics:* Use bar plots instead of tables unless the tables are
     really simple (less than 3-4 rows, and columns). Pie charts are
     also near useless - they worked here only because you had only 2
     categories per chart.
  4) Especially when masked, *diction* is important. When presenting,
     speak slowly, more measured, repeat main points etc. I am setting
     a bad example[fn:3].

  All in all, this was a fantastic presentation, excellently sourced
  and delivered, and the questions were well answered and dealt with.

  I really enjoyed it - I'm only sorry that I talked so much. You
  opened that Pandora box when you permitted questions
  throughout. Hope that others will ask more questions in future
  presentations!

* [[https://github.com/birkenkrahe/ai482/blob/main/presentations/AI%20in%20soccer%20to%20improve%20athlete%20performance%20DUE%20Nov%2015%20(1).pdf][AI in soccer to improve athlete performance (Emma Brandes, 15-Oct-2021)]]

  Emma presented really interesting, current examples, compared them
  and gave us a timeline for these performance and player
  performance-oriented applications. She gathered primary data (from
  team mates and from her own experience). Excellent amount of
  material for session and discussion. The discussion focused on the
  actual advantage of these applications for the player, and on the
  potential loss of playing skills through data overload. Really
  enjoyed the illustration through devices brought to class and
  through the video selection.

  Points of improvement:

  1) when talking stats, *show* some stats (numbers, tables etc.)
  2) give a better idea on how these devices yield better player
     performance (beyond the commercial hype)
  3) a little more *technical* insight - what exactly is AI here? One
     could e.g. apply models that we have already learnt about, like
     PEAS for intelligent agents. Are these intelligent agents?
  4) *References* ought to include video and image material

* [[https://github.com/birkenkrahe/ai482/blob/main/presentations/Presentation-DatO.pdf][Problem Solving & Searching Algorithms (Dat O, 22-Oct-2021)]]

  This presentation was based on chapter 3 (pp. 81-128) of AIMA. Like
  all full chapters in the textbook, it packed a punch - I could
  easily lecture for a week on every one of the 6 sub chapters[fn:4].

  Dat did an amazing job of giving an overview of a vast field. He
  connected the presented material to previous courses (like
  algorithms, data structures etc.), and chose illustrations taken
  from educational videos.

  I thought it was a thorough introduction that left out exactly what
  needed to be left out. Dat used almost the entire time but we still
  got to discuss several interesting issues at the end, like:

  * Which skills do you need to work with these algorithms in practice?
  * How much research (if any) is still done in this area (much of it
    is part of the compsci undergraduate curriculum)?
  * Which algorithms are used in which current AI applications?

  Especially the last question will be relevant to other presenters as
  well. Because there is so much more in this chapter, it will be
  useful to you to read it - and much easier now that Dat has given us
  an overview.

  The solo presentation is also a good stepping stone on his way to
  the final presentation and prototype, which will deal with genetic
  algorithms.

  Points of improvement: almost none. I had wished to see some
  implementations (as in: code) for the benefit of those who know how
  to write and read code. In AIMA, this is done using pseudocode.

  A little more thought about how to get the audience involved would
  have improved this presentation even more. This could go as far as
  to give them a small task and ask for example, which algorithm would
  be suitable for a given sample problem.

  Lastly, the examples could have been presented in a closed form -
  such a slide would have been easy to memorize. A number of
  interesting examples were mentioned. And also - storytelling - but
  to turn the presentation of algorithms into a story would have been
  a completely different presentation (the easiest way is probably by
  presenting the development timeline - when an algorithm was first
  developed, improved, used etc.)

* Augmented reality (Amber McClurg, 12-Nov-2021)

  After Amber's presentation on the [[https://github.com/birkenkrahe/ai482/blob/main/presentations/solo/Therapeutic%20Potential%20of%20VR%20McClurg.pdf][therapeutic potential of VR]], we
  watched a couple of stupid Facebook (aka "Meta") videos. Here are
  the two films that I kept talking about and did not show:

  This is Mark Zuckerberg's presentation on the "metaverse" project(s)
  for developers and tech people rather than consumers (at least I
  think that's the target audience because it's longer and much more
  detailed): "[[https://youtu.be/gElfIo6uw4g][Everything Facebook revealed about the Metaverse in 11
  minutes" (2021)]]. I found it via this very negative review ("[[https://onezero.medium.com/i-want-no-part-of-our-impending-metaverse-future-459678bb3cc5][The demo
  of Zuckerberg's dream was a nightmare]]")

  And here is [[https://vimeo.com/46304267]["Sight" (2012)]]. While dated as a film, it is astonishing
  how Facebook (and others) are only now talking about getting this
  type of technology into the home. Really, this is not just
  augmented, but neurally linked, wearable technology. The film's
  ending is ultimately terribly depressing.

  I mentioned my experiments with an internship course of
  internationally placed seniors in Germany, which took place in
  Second Life. I made [[https://vimeo.com/19037369][this video]] for a conference and to attract
  students (2011). My own avatar was a bearded centaur with wings.

  I remain un/surprised that VR/AR has not become more
  widespread. This is not our primary concern for this course, since
  the overlap with AI is sporadic at best, but it could be a possible
  scenario for many AI apps whose appeal rests on a similar value
  proposition: to take people out of their real lives and insert them
  into a virtual reality (which the internet, by the way, is not
  because it is not fully immersive).

* References

  CNET (Oct 28, 2021). Everything Facebook revealed about the
  Metaverse in 11 minutes [video]. [[https://youtu.be/gElfIo6uw4g][URL: youtu.be/gElfIo6uw4g]].

  Robot Genius (2012). Sight [video]. [[https://vimeo.com/46304267][URL: vimeo.com.]]

  Stephen Moore (Oct 29 2021). I Want No Part of Our Impending
  Metaverse Future The demo of Zuckerberg’s dream was a nightmare
  [blog]. URL: [[https://onezero.medium.com/i-want-no-part-of-our-impending-metaverse-future-459678bb3cc5][onezero.medium.com.]]

* Footnotes

[fn:4]I had meant to work through the chapter weeks ago but then one
thing happened and then another and I didn't get to reading through it
until shortly before the presentation, and I found it very difficult,
even with my background. A lot of the descriptions and examples in
AIMA are exceptionally dense. Several of the footnotes and the
bibliography hide recent research and are state-of-the-art. AIMA is
definitely not a typical textbook in this regard - just like AI is not
a typical course topic (because it's evolving so fast in front of your
very eyes!).

[fn:3]I really don't have any excuses: foreigners and teachers should
be held to much more stringent presentation standards. Alas, because
we speak so much, and audiences are often silent and forgiving (unlike
in business), bad habits tend to fester. Also, many teachers are
resistant to change.

[fn:2]In fact, at second thought, it would have been better to choose
either essay or presentation mode.

[fn:1]Remember: unless explicitly noted, the assumption is that lists
are ordered. The human mind orders them automatically from top to
bottom. Keep this in mind by using numbering and by putting the most
important stuff to the top (especially important in presentations
because people run out of time towards the end of slides and/or
presentations).
