#+startup: overview
* Session Protocols

  Post your protocol here. Take a look at [[https://github.com/birkenkrahe/ai482/blob/main/2_what_is_ai/protocol_23_aug.md][my example protocol]].

* AI in the military (Jacob Sampley, 13-Oct-2021)

  This presentation was totally worth staying up for all night - very
  well done (apart from Jacob's time mgmt prior to the presentation
  ;-). A great start to the solo presentation series! Jacob really
  used his time well: the number of slides was just right for 45
  min. 30 min speaking + discussion.

  I hope to pick this up at the start on Wed, perhaps re: technology,
  because we didn't talk about that at all.

  Some potential points of improvement[fn:1]:

  1) There was a clear *research question*, in the subtitle (perhaps
     even a *hypothesis*?). It would have been good to directly answer
     it at the end, "main message" style. Like a paper, a presentation
     benefits from a summary/conclusion. All the information was
     there, on the slides, which were partly organized like a
     paper[fn:2].
  2) *Audience interaction*: questions to the audience should always
     be *open questions* if you want a discussion, and only closed
     questions for a poll-like interaction (which does wake people
     up): it's sometimes good to ask these throughout the talk.
  3) *Graphics:* Use bar plots instead of tables unless the tables are
     really simple (less than 3-4 rows, and columns). Pie charts are
     also near useless - they worked here only because you had only 2
     categories per chart.
  4) Especially when masked, *diction* is important. When presenting,
     speak slowly, more measured, repeat main points etc. I am setting
     a bad example[fn:3].

  All in all, this was a fantastic presentation, excellently sourced
  and delivered, and the questions were well answered and dealt with.
  
  I really enjoyed it - I'm only sorry that I talked so much. You
  opened that Pandora box when you permitted questions
  throughout. Hope that others will ask more questions in future
  presentations!

* AI in soccer to improve athlete performance (Emma Brandes, 15-Oct-2021)

  Emma presented really interesting, current examples, compared them
  and gave us a timeline for these performance and player
  performance-oriented applications. She gathered primary data (from
  team mates and from her own experience). Excellent amount of
  material for session and discussion. The discussion focused on the
  actual advantage of these applications for the player, and on the
  potential loss of playing skills through data overload. Really
  enjoyed the illustration through devices brought to class and
  through the video selection.

  Points of improvement:

  1) when talking stats, *show* some stats (numbers, tables etc.)
  2) give a better idea on how these devices yield better player
     performance (beyond the commercial hype)
  3) a little more *technical* insight - what exactly is AI here? One
     could e.g. apply models that we have already learnt about, like
     PEAS for intelligent agents. Are these intelligent agents? 
  4) *References* ought to include video and image material
  
* Footnotes

[fn:3]I really don't have any excuses: foreigners and teachers should
be held to much more stringent presentation standards. Alas, because
we speak so much, and audiences are often silent and forgiving (unlike
in business), bad habits tend to fester. Also, many teachers are
resistant to change.

[fn:2]In fact, at second thought, it would have been better to choose
either essay or presentation mode.

[fn:1]Remember: unless explicitly noted, the assumption is that lists
are ordered. The human mind orders them automatically from top to
bottom. Keep this in mind by using numbering and by putting the most
important stuff to the top (especially important in presentations
because people run out of time towards the end of slides and/or
presentations).
