#+TITLE:Future of AI
#+AUTHOR: Marcus Birkenkrahe
#+Subtitle: Seminar on Artificial Intelligence
#+OPTIONS: toc:nil num:nil ^:nil
#+INFOJS_OPT: :view:info

As always, this framework presentation will be fully equipped with
more material after the live classroom session on Oct 6, 2021.

   * Protocol anyone?
   * Whiteboard photos

* What will you learn?

  * Broaden the view from Andrew Ng's focus
  * Check impact of intelligent agent paradigm
  * Understand method/content/impact of [[ai100][AI100 (2021)]]
  * Develop AI literacy (critical thinking)
  * Quick group exercise to check understanding OR
  * Hard philosopho-technical question to brood over

* Data

** Definition

  #+begin_quote
  "Artificial intelligence is about getting a machine to carry out
  behaviors that we think of as requiring intelligence."
  #+end_quote

  "AI effect:" once a problem is solved by AI, it is no longer
  considered an AI problem - e.g. "real-time navigation aids that
  decide when and how to describe upcoming turns to guide you to your
  destination."

** Goals

   * Impact of AI on people and societies worldwide
   * Articulate "standing questions"
   * Initiate discussion
   * Influence policy and curricular decisions

** Method

   Remember common critical questions: relevance (how important is
   it?) and validation (why should I trust it?)

   | Longitudinal study (started in 2016)                                 | ? |
   | Multi-disciplinary expert panel (p.3)[fn:1]                          | ? |
   | Experts "create AI algorithms" or "study their influence on society" | ? |
   | Multi-step process of linked workshops[fn:2]                         | ? |

   Compare: Royal Dutch Shell scenario planning process ([[https://youtu.be/yVgxZnRT54E][FFFatMIT,
   2011]])

** Output

   | 70 page document                                               | ? |
   | Panel discussion videos                                        | ? |
   | List of 12 standing questions                                  | ? |
   | Limited quantitative data 2 graphs (p.44,p.57), 1 table (p.66) | ? |
   | Illustrations through various (well-known) pictures            | ? |
   | References (in footnotes) often just URLs                      | ? |

* Information

  Standing Questions (SQ):

  1) What are some Pictures that reflect important AI progress?
  2) What are the most important advances in AI?
  3) What are the most inspiring open grand challenge problems?
  4) How much have we progressed in understanding the key mysteries of
     human intelligence?
  5) What are the prospects for more general artificial intelligence?
  6) How has public sentiment towards AI evolved, and how should we
     inform/educate the public?
  7) How should governments act to ensure AI is developed and used
     responsibly?
  8) What should the roles of academia and industry be, respectively,
     in the development and deployment of AI technologies and the
     study of the impacts of AI?
  9) What are the most promising opportunities for AI?
  10) What are the most pressing dangers of AI?
  11) How has AI impacted socioeconomic relationships?
  12) Does it appear "building in how we think" works as an
      engineering strategy in the long run?

  Check some of these out for relevance to your presentation topics
  (some interesting references though overall lack of quantitative
  data).

* Knowledge

  Place SQs in scenario framework: 
  * problem vs. solution focus
  * soft (socio-political) vs. hard (mathematical-technical)

  Result:
  * Soft problems: 4,5,6,10,11
  * Soft solutions: 1,7,8
  * Hard problems: 3
  * Hard solutions: 2,9,12

* Wisdom

  Question: What is the relationship between AI and God (if any)?

  #+begin_quote
  “It’s only for me, and — but I but I personally think of my belief
  that God exists, although I have no idea what that means. But I
  believe that there is something beyond human capabilities — and it
  might be some AI, but whatever, but I do believe that there is
  something that goes beyond the realm of human understanding, that I
  can try to learn more about how to resonate with, whatever that
  being would like me to do.” [[knuth][Donald Knuth (2021)]]
  #+end_quote

  See also podcast summary ([[zdnet][McKendrick, 2021]]).

* References

  <<ai100>> Litman et al (Sept 16, 2021). Gathering Strength,
  Gathering Storms: The One Hundred Year Study on Artificial
  Intelligence (AI100). 2021 Study Panel Report, Stanford U.,
  CA. [[https://ai100.stanford.edu/sites/g/files/sbiybj18871/files/media/file/AI100Report_MT_10.pdf][Online: ai100.stanford.edu]].

  <<knuth>> Fridman L (Sept 9, 2021). Donald Knuth: Programming,
  Algorithms, Hard Problems & the Game of Life | Lex Fridman Podcast
  #219 [Podcast]. [[https://lexfridman.com/donald-knuth-2/][Online: lexfridman.com]].

  <<zdnet>>> McKendrick J (Sept 18, 2021). Artificial intelligence
  success is tied to ability to augment, not just automate
  [Website]. [[https://www.zdnet.com/article/artificial-intelligence-success-is-tied-to-ability-to-augment-not-just-automate/][Online:zdnet.com]].

  <<ng>> Stanford HAI (Sep 23, 2020). Andrew Ng: Bridging AI's
  Proof-of-Concept to Production Gap [video]. [[https://youtu.be/tsPuVAMaADY][Online: youtube.com]].

  Warden P (Feb 3, 2021). The Future of Machine Learning is Tiny
  [Blog]. [[https://www.arducam.com/raspberry-pi-pico-tensorflow-lite-micro-person-detection-arducam/][Online: arducam.com]].

* Footnotes

[fn:2]"Two workshops were selected for funding:"

[fn:1]Though the authors claim that the 2nd report 2021 should broaden
the vision of AI beyond "North American cities" (2016), there are no
Standing Committee members from Continental Europe, or from
Asia. While Microsoft Research is participating, Google and Amazon are
absent.
